
package JPanel_Admin;

import Dao.TaiKhoanDao;
import Model.TaiKhoanModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class TaiKhoanJPanel_Admin extends javax.swing.JPanel {

    
    DefaultTableModel tblTKModel = new DefaultTableModel();
    ArrayList <TaiKhoanModel> arr;
    int row;
    String maTK;
    
    public TaiKhoanJPanel_Admin() {
        
        initComponents();
        loadData();
        loadComboBox();
    }
    public void loadComboBox(){
        TaiKhoanDao tkDao = new TaiKhoanDao();
        arr = tkDao.loadComboBox();
        
        for(int i = 0; i < arr.size(); i++)
        {
            cbVaiTro.addItem(arr.get(i).getROLE());
        }
    }
    public void loadData(){
        tblTKModel = (DefaultTableModel)tblTK.getModel();
        tblTKModel.setRowCount(0);
        TaiKhoanDao tkDao = new TaiKhoanDao();
        arr = tkDao.docDanhMuc();
        
        String tieude[] = {"Tên đăng nhập", "Mật khẩu", "Vai trò"};
        tblTKModel.setColumnIdentifiers(tieude);
        
        for(int i = 0; i <arr.size();i++)
        {
            Vector<Object> vec = new Vector<>();
            vec.add(arr.get(i).getTENDN());
            vec.add(arr.get(i).getMATKHAU());
            vec.add(arr.get(i).getROLE());
            
            tblTKModel.addRow(vec);
        }
    }
    
    
    public void loadData_1(String TenDN){
        if(txtNhapTaiKhoan.getText().equals("")){
            return;
        }
        else{
            TenDN = txtNhapTaiKhoan.getText();
            
            tblTKModel = (DefaultTableModel) tblTK.getModel();
            tblTKModel.setRowCount(0);
            TaiKhoanDao tkDao = new TaiKhoanDao();
            arr = tkDao.Search(TenDN);
            
            String tieude[] = {"Tên đăng nhập", "Mật khẩu", "Vai trò"};
            tblTKModel.setColumnIdentifiers(tieude);
            
            if(arr.size()>0){
                for(int i = 0; i<arr.size(); i++){
                    Vector<Object> vec = new Vector<>();
                    
                    vec.add(arr.get(i).getTENDN());
                    vec.add(arr.get(i).getMATKHAU());
                    vec.add(arr.get(i).getROLE());
                    
                    tblTKModel.addRow(vec);
                }
                jlbTT.setText("Thành công");
                jlbTT.setForeground(new Color(11,194,106));
            }
            else{
                jlbTT.setText("Không thành công!");
                jlbTT.setForeground(Color.red);
                loadData();
                
            }
            
        }
    }
    
    private void xoaTrang(){
        txtTenDN.setText("");
        txtMatKhau.setText("");
        cbVaiTro.setSelectedItem("Nhân Viên");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNhapTaiKhoan = new javax.swing.JTextField();
        btnTimTaiKhoan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTK = new javax.swing.JTable();
        btnThemaiKhoan = new javax.swing.JButton();
        btnXoaTaiKhoan = new javax.swing.JButton();
        btnSuaTaiKhoan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDN = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jlbTT = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbVaiTro = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(766, 588));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(766, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(11, 194, 106));
        jLabel1.setText("TÀI KHOẢN");
        jLabel1.setMaximumSize(new java.awt.Dimension(135, 29));
        jLabel1.setMinimumSize(new java.awt.Dimension(135, 29));
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 29));

        jSeparator1.setBackground(new java.awt.Color(11, 194, 106));
        jSeparator1.setForeground(new java.awt.Color(11, 194, 106));

        txtNhapTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNhapTaiKhoan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNhapTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNhapTaiKhoanMouseClicked(evt);
            }
        });
        txtNhapTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhapTaiKhoanActionPerformed(evt);
            }
        });

        btnTimTaiKhoan.setBackground(new java.awt.Color(11, 194, 106));
        btnTimTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnTimTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnTimTaiKhoan.setText("Tìm kiếm");
        btnTimTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTaiKhoanActionPerformed(evt);
            }
        });

        tblTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên đăng nhập", "Mặt khẩu", "Vai trò"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTK);

        btnThemaiKhoan.setBackground(new java.awt.Color(11, 194, 106));
        btnThemaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnThemaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnThemaiKhoan.setText("Thêm");
        btnThemaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemaiKhoanActionPerformed(evt);
            }
        });

        btnXoaTaiKhoan.setBackground(new java.awt.Color(11, 194, 106));
        btnXoaTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnXoaTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaTaiKhoan.setText("Xóa");
        btnXoaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTaiKhoanActionPerformed(evt);
            }
        });

        btnSuaTaiKhoan.setBackground(new java.awt.Color(11, 194, 106));
        btnSuaTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnSuaTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaTaiKhoan.setText("Sửa");
        btnSuaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTaiKhoanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Tên đăng nhập:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Mật khẩu:");

        txtTenDN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTenDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenDNMouseClicked(evt);
            }
        });

        txtMatKhau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMatKhauMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Trạng thái: ");

        jlbTT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Vai trò:");

        cbVaiTro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbVaiTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVaiTroActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(11, 194, 106));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Làm mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtNhapTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btnTimTaiKhoan))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnXoaTaiKhoan)
                                .addGap(18, 18, 18)
                                .addComponent(btnThemaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSuaTaiKhoan))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbVaiTro, 0, 228, Short.MAX_VALUE)
                                            .addComponent(txtTenDN))
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbTT, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimTaiKhoan)
                    .addComponent(txtNhapTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemaiKhoan)
                    .addComponent(btnXoaTaiKhoan)
                    .addComponent(btnSuaTaiKhoan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbTT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, 774, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNhapTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhapTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhapTaiKhoanActionPerformed

    private void btnThemaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemaiKhoanActionPerformed
        TaiKhoanModel tk = new TaiKhoanModel();
        if(txtTenDN.getText().equals("")||txtMatKhau.getText().equals("")){
            jlbTT.setText("Bạn cần nhập đủ dữ liệu!");
            jlbTT.setForeground(Color.red);
            return;
        }
        else{
            tk.setTENDN(txtTenDN.getText());
            tk.setMATKHAU(txtMatKhau.getText());
            tk.setROLE(cbVaiTro.getSelectedItem().toString());
            tk.setTINHTRANG(1);
            
            TaiKhoanDao tkDao = new TaiKhoanDao();
            if(tkDao.AddTK(tk) > 0){
                jlbTT.setText("Thành công");
                jlbTT.setForeground(new Color(11,194,106));
                xoaTrang();
                tblTKModel.setRowCount(0);
                loadData();
            }
            else{
                jlbTT.setText("Không thành công!");
                jlbTT.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_btnThemaiKhoanActionPerformed

    private void btnXoaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTaiKhoanActionPerformed
         int index = tblTK.getSelectedRow();
        if(index == -1){
            jlbTT.setText("Vui lòng chọn 1 Khách Hàng trong bảng để xóa!");
            jlbTT.setForeground(Color.red);
            return;
        }
        TaiKhoanDao tkDao = new TaiKhoanDao();
        int tk = JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa không","Xác nhận" ,JOptionPane.YES_NO_OPTION);
        if(tk == JOptionPane.YES_OPTION){
            if(tkDao.DeleteTK(tblTK.getValueAt(index, 0).toString())){
                jlbTT.setText("Thành công");
                jlbTT.setForeground(new Color(11,194,106));
                xoaTrang();
                tblTKModel.setRowCount(0);
                loadData();
            }
            else{
                jlbTT.setText("Không thành công!");
                jlbTT.setForeground(Color.red);
            }      
        }
    }//GEN-LAST:event_btnXoaTaiKhoanActionPerformed

    private void tblTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTKMouseClicked
         if(tblTK.getSelectedRow() >= 0){
            maTK = tblTK.getValueAt(tblTK.getSelectedRow(), 0) + "";
            txtTenDN.setText(tblTK.getValueAt(tblTK.getSelectedRow(), 0) + "");
            txtMatKhau.setText(tblTK.getValueAt(tblTK.getSelectedRow(), 1) + "");
            cbVaiTro.setSelectedItem(tblTK.getModel().getValueAt(tblTK.getSelectedRow(),2));
        }
        jlbTT.setText("");
    }//GEN-LAST:event_tblTKMouseClicked

    private void btnSuaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTaiKhoanActionPerformed
        TaiKhoanModel tk = new TaiKhoanModel();
        if(txtTenDN.getText().equals("")||txtMatKhau.getText().equals("")){
            jlbTT.setText("Bạn cần nhập đủ dữ liệu!");
            jlbTT.setForeground(Color.red);
            return;
        }
        else{
            tk.setTENDN(txtTenDN.getText());
            tk.setMATKHAU(txtMatKhau.getText());
            tk.setROLE(cbVaiTro.getSelectedItem().toString());
            tk.setTINHTRANG(0);
            
            TaiKhoanDao tkDao = new TaiKhoanDao();
            //ktra ten dang nhap
            boolean chk = false;
            if(tk.getTENDN().equals(maTK)){
                chk = true;
            }
            
            System.out.println(maTK);
            System.out.println(tk.getTENDN());
            
            if(chk == true){
               if(tkDao.UpdateTK(tk) > 0){
                   jlbTT.setText("Thành công");
                   jlbTT.setForeground(new Color(11,194,106));
                   xoaTrang();
                   tblTKModel.setRowCount(0);
                   
                   if(txtNhapTaiKhoan.getText().equals("")){
                       loadData();
                   }
                   else{
                       loadData_1(txtNhapTaiKhoan.getText());
                   }
               }
            }
            else{
                jlbTT.setText("Không thành công!");
                jlbTT.setForeground(Color.red);
                
                return;
          }
        }
       
    }//GEN-LAST:event_btnSuaTaiKhoanActionPerformed

    private void btnTimTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimTaiKhoanActionPerformed
        xoaTrang();
        if(txtNhapTaiKhoan.getText().equals("")){
            jlbTT.setText("Không thành công!");
            jlbTT.setForeground(Color.red);
            loadData();
        }else{
            jlbTT.setText("Thành công");
            jlbTT.setForeground(new Color(11,194,106));
            loadData_1(txtNhapTaiKhoan.getText());
        }
    }//GEN-LAST:event_btnTimTaiKhoanActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        xoaTrang();
        loadData();
        txtNhapTaiKhoan.setText("");
        jlbTT.setText("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void cbVaiTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVaiTroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVaiTroActionPerformed

    private void txtNhapTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNhapTaiKhoanMouseClicked
        jlbTT.setText("");
    }//GEN-LAST:event_txtNhapTaiKhoanMouseClicked

    private void txtTenDNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenDNMouseClicked
        jlbTT.setText("");
    }//GEN-LAST:event_txtTenDNMouseClicked

    private void txtMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMatKhauMouseClicked
        jlbTT.setText("");
    }//GEN-LAST:event_txtMatKhauMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSuaTaiKhoan;
    private javax.swing.JButton btnThemaiKhoan;
    private javax.swing.JButton btnTimTaiKhoan;
    private javax.swing.JButton btnXoaTaiKhoan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbVaiTro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlbTT;
    private javax.swing.JTable tblTK;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNhapTaiKhoan;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
