/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel_Admin;

import ConnectDatabase.ConnectDB;
import Dao.TauDao;
import Model.TauModel;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
public class TauJPanel_Admin1 extends javax.swing.JPanel{

    /**
     * Creates new form TauJPanel_Admin
     */
    DefaultTableModel tblTAUModel = new DefaultTableModel();
    ArrayList<TauModel> arr;
    int row;
    String maTau = "";
   
    public TauJPanel_Admin1() {
        initComponents();
        loadData();
        loadCombobox();
        txtTongSoGhe.setEditable(false);
        txtNhapMaTau.setEditable(false);
        
    }
    
    public void loadCombobox(){
        TauDao tauDao = new TauDao();
        arr = tauDao.loadComboBox();
        
       
        for(int i = 0; i < arr.size(); i++){
            cbHangSX.addItem(arr.get(i).getHANGSX());
        }
    }
    
    // Hien thi du lieu len table
    public void loadData(){
        tblTAUModel = (DefaultTableModel)jTable1.getModel();
        tblTAUModel.setRowCount(0);
        TauDao tauDao = new TauDao();
        arr = tauDao.docDanhMuc();
        
        String tieude[] = {"MATAU", "Tên tàu", "Hãng sản xuất", "Số ghế L1", "Số ghế L2", "Tổng số ghế", "Tình trạng"};
        tblTAUModel.setColumnIdentifiers(tieude);
        
        for(int i = 0; i < arr.size(); i++){
            
            Vector<Object> vec = new Vector<>();
            
            vec.add(arr.get(i).getMATAU());
            vec.add(arr.get(i).getTENTAU());
            vec.add(arr.get(i).getHANGSX()) ;
            vec.add(arr.get(i).getSOGHEL1()) ;
            vec.add(arr.get(i).getSOGHEL2()) ;
            vec.add(arr.get(i).getTONGSOGHE()) ;
            vec.add(arr.get(i).getTINHTRANG()) ;
            
            tblTAUModel.addRow(vec);
        }
    }  
    
    public void loadData_1(String maTAU){
        if(txtNhapMATAU.getText().equals("")){
            return;
        }
        else{
            maTAU = txtNhapMATAU.getText();
            
            tblTAUModel = (DefaultTableModel)jTable1.getModel();
            tblTAUModel.setRowCount(0);
            TauDao tauDao = new TauDao();
            arr = tauDao.Search(maTAU);

            String tieude[] = {"MATAU", "Tên tàu", "Hãng sản xuất", "Số ghế L1", "Số ghế L2", "Tổng số ghế", "Tình trạng"};
            tblTAUModel.setColumnIdentifiers(tieude);
            
            if(arr.size() > 0){
                for(int i = 0; i < arr.size(); i++){

                    Vector<Object> vec = new Vector<>();

                    vec.add(arr.get(i).getMATAU());
                    vec.add(arr.get(i).getTENTAU());
                    vec.add(arr.get(i).getHANGSX()) ;
                    vec.add(arr.get(i).getSOGHEL1()) ;
                    vec.add(arr.get(i).getSOGHEL2()) ;
                    vec.add(arr.get(i).getTONGSOGHE()) ;
                    vec.add(arr.get(i).getTINHTRANG()) ;
            
                    tblTAUModel.addRow(vec);
                }
                jlbTT.setText("Thành Công");
                jlbTT.setForeground(new Color(11,194,106));
                
            }
            else{
                jlbTT.setText("Không thành công");
                jlbTT.setForeground(Color.red);
                loadData();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        btnThemTau = new javax.swing.JButton();
        txtSoGheL2 = new javax.swing.JTextField();
        btnXoaTau = new javax.swing.JButton();
        btnSuaTau = new javax.swing.JButton();
        txtTongSoGhe = new javax.swing.JTextField();
        btnTimMaTau = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNhapMATAU = new javax.swing.JTextField();
        cbHangSX = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNhapMaTau = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtTinhTrangTau = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTenTau = new javax.swing.JTextField();
        jlbTT = new javax.swing.JLabel();
        btnRefreshTau = new javax.swing.JButton();
        txtSoGheL1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(766, 588));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(766, 0));

        jSeparator1.setBackground(new java.awt.Color(11, 194, 106));
        jSeparator1.setForeground(new java.awt.Color(11, 194, 106));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Tổng ghế:");

        btnThemTau.setBackground(new java.awt.Color(11, 194, 106));
        btnThemTau.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnThemTau.setForeground(new java.awt.Color(255, 255, 255));
        btnThemTau.setText("Thêm");
        btnThemTau.setToolTipText("");
        btnThemTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTauActionPerformed(evt);
            }
        });

        txtSoGheL2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSoGheL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSoGheL2MouseClicked(evt);
            }
        });

        btnXoaTau.setBackground(new java.awt.Color(11, 194, 106));
        btnXoaTau.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnXoaTau.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaTau.setText("Xóa");
        btnXoaTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTauActionPerformed(evt);
            }
        });

        btnSuaTau.setBackground(new java.awt.Color(11, 194, 106));
        btnSuaTau.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnSuaTau.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaTau.setText("Sửa");
        btnSuaTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTauActionPerformed(evt);
            }
        });

        txtTongSoGhe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTongSoGhe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTongSoGheMouseClicked(evt);
            }
        });

        btnTimMaTau.setBackground(new java.awt.Color(11, 194, 106));
        btnTimMaTau.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnTimMaTau.setForeground(new java.awt.Color(255, 255, 255));
        btnTimMaTau.setText("Tìm kiếm");
        btnTimMaTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimMaTauActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Hãng sản xuất:");

        txtNhapMATAU.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNhapMATAU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNhapMATAUMouseClicked(evt);
            }
        });

        cbHangSX.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbHangSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHangSXActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Mã tàu:");

        txtNhapMaTau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNhapMaTau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNhapMaTauMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Tình trạng:");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MATAU", "Tên tàu", "Hãng sản xuất", "Số ghế L1", "Số ghế L2", "Tổng số ghế", "Tình trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Số ghế L1:");

        txtTinhTrangTau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTinhTrangTau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTinhTrangTauMouseClicked(evt);
            }
        });
        txtTinhTrangTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinhTrangTauActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Tên tàu:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(11, 194, 106));
        jLabel1.setText("TÀU");
        jLabel1.setMaximumSize(new java.awt.Dimension(135, 29));
        jLabel1.setMinimumSize(new java.awt.Dimension(135, 29));
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Số ghế L2:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Trạng thái:");

        txtTenTau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTenTau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenTauMouseClicked(evt);
            }
        });

        jlbTT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnRefreshTau.setBackground(new java.awt.Color(11, 194, 106));
        btnRefreshTau.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnRefreshTau.setForeground(new java.awt.Color(255, 255, 255));
        btnRefreshTau.setText("Làm mới");
        btnRefreshTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTauActionPerformed(evt);
            }
        });

        txtSoGheL1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSoGheL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSoGheL1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtTenTau, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNhapMaTau, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnXoaTau, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnThemTau)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSuaTau, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTongSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbHangSX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtSoGheL1)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSoGheL2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                            .addComponent(txtTinhTrangTau)))))
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jlbTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(190, 190, 190)
                                .addComponent(btnRefreshTau))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNhapMATAU, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(btnTimMaTau)))
                        .addGap(3, 3, 3)))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTimMaTau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNhapMATAU, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnXoaTau)
                                    .addComponent(btnThemTau)
                                    .addComponent(btnSuaTau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNhapMaTau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSoGheL1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(3, 3, 3)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenTau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTongSoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSoGheL2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTinhTrangTau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshTau)
                    .addComponent(jLabel9)
                    .addComponent(jlbTT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void xoaTrang(){
        txtNhapMaTau.setText("");
        txtTenTau.setText("");
        txtTongSoGhe.setText("");
        txtSoGheL1.setText("");
        txtSoGheL2.setText("");
        cbHangSX.setSelectedItem("diesel DMU");
        txtTinhTrangTau.setText("");
    }
    
    /*private boolean ktrSDT(String s) throws PhoneException{
        String reg = "^(0|\\+84)(\\s|\\.)?((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\\d)(\\s|\\.)?(\\d{3})(\\s|\\.)?(\\d{3})$";
        boolean kt = s.matches(reg);
        
        if(kt == true && s.length() == 10)
            return true;
        return false;
    }*/
    
    private boolean ktrKiTuDacBiet(String s){
        //  ktr ki tu dac biet
        Pattern p = Pattern.compile("[^A-Za-z0-9]");
        Matcher m = p.matcher(s);
        
        // ktr so
        
        
        for (int i = 0; i < s.length(); i++) {
            if (Character.isLetter(s.charAt(i))) {
                return false;
            }
            if (i + 1 == s.length()) {
                return true && m.find() == false;
            }
        } 
        
        return  false;
    }
    private void btnSuaTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTauActionPerformed
        // TODO add your handling code here:
        TauModel tau = new TauModel();
        if(txtTenTau.getText().equals("") || txtTongSoGhe.getText().equals("") || txtSoGheL1.getText().equals("") || txtSoGheL2.getText().equals("") || cbHangSX.getSelectedItem().toString().equals("") || txtTinhTrangTau.getText().equals("")){
            jlbTT.setText("Bạn cần nhập đủ dữ liệu");
            jlbTT.setForeground(Color.red);
            return;
        }
        
        // ktr sdt
        /*try {
            if(ktrSDT(txtNhapSDT.getText()) == false){
                jlbTT.setText("SĐT không hợp lệ");
                jlbTT.setForeground(Color.red);
                return;
            }
        } catch (PhoneException ex) {
            System.out.println(ex.getMessage());
        }*/
        
        //ktr ki tu dac biet trong Vi
        if(ktrKiTuDacBiet(txtSoGheL1.getText()) == false || ktrKiTuDacBiet(txtSoGheL2.getText()) == false || ktrKiTuDacBiet(txtTinhTrangTau.getText()) == false){
            jlbTT.setText("Số lượng không hợp lệ");
            jlbTT.setForeground(Color.red);
            return;
        }
        else if(Integer.parseInt(txtSoGheL1.getText())<0||Integer.parseInt(txtSoGheL2.getText())<0||Integer.parseInt(txtTinhTrangTau.getText()) < 0 || Integer.parseInt(txtTinhTrangTau.getText()) >=2)
        {
            jlbTT.setText("Số lượng không hợp lệ");
            jlbTT.setForeground(Color.red);
            return;
        }
        else{
            tau.setMATAU(txtNhapMaTau.getText());
            tau.setTENTAU(txtTenTau.getText());
            tau.setHANGSX(cbHangSX.getSelectedItem().toString());
            tau.setSOGHEL1(Integer.parseInt(txtSoGheL1.getText()));
            tau.setSOGHEL2(Integer.parseInt(txtSoGheL2.getText()));
            int TongSoGheTemp=Integer.parseInt(txtSoGheL1.getText())+Integer.parseInt(txtSoGheL2.getText());
            tau.setTONGSOGHE(TongSoGheTemp);
            tau.setTINHTRANG(Integer.parseInt(txtTinhTrangTau.getText()));

            


            TauDao tauDao = new TauDao();
            
//            // Ktr MATAU
//            boolean chk = false;
//            if(tau.getMATAU().equals(maTau)){
//                chk = true;
//            }
            

            if(tauDao.UpdateTau(tau) > 0){
                jlbTT.setText("Thành Công");
                jlbTT.setForeground(new Color(11,194,106));
                xoaTrang();
                tblTAUModel.setRowCount(0);

                if(txtNhapMATAU.getText().equals("")){
                    loadData();
                }
                else{
                    loadData_1(txtNhapMATAU.getText());
                }
            }
            else{
                jlbTT.setText("Không thành công");
                jlbTT.setForeground(Color.red);
                
                return;
            }
        }
    }//GEN-LAST:event_btnSuaTauActionPerformed

    private void btnXoaTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTauActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        if (index == -1) {
            jlbTT.setText("Vui lòng chọn 1 Tàu trong bảng để xóa");
            jlbTT.setForeground(Color.red);
            return;
        }
        TauDao tauDao = new TauDao();
        
        int tk = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không","Xác nhận" ,JOptionPane.YES_NO_OPTION);
        if (tk==JOptionPane.YES_OPTION)  
        {
            if (tauDao.DeleteTau(jTable1.getValueAt(index,0).toString()))
            {
                jlbTT.setText("Thành Công");
                jlbTT.setForeground(new Color(11,194,106));
                xoaTrang();
                tblTAUModel.setRowCount(0);
                loadData();
            } else {
                jlbTT.setText("Không thành công");
                jlbTT.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_btnXoaTauActionPerformed

    private void btnThemTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTauActionPerformed
        // TODO add your handling code here:
        TauModel tau = new TauModel();
        
        if( txtTenTau.getText().equals("") || txtSoGheL1.getText().equals("") || txtSoGheL2.getText().equals("") || cbHangSX.getSelectedItem().toString().equals("") || txtTinhTrangTau.getText().equals("")){
            jlbTT.setText("Bạn cần nhập đủ dữ liệu");
            jlbTT.setForeground(Color.red);
            return;
        }
        
        /*// ktr sdt
        try {
            if(ktrSDT(txtNhapSDT.getText()) == false){
                jlbTT.setText("SĐT không hợp lệ");
                jlbTT.setForeground(Color.red);
                return;
            }
        } catch (PhoneException ex) {
            System.out.println(ex.getMessage());
        }*/
        
        //ktr ki tu dac biet trong Vi
        if(ktrKiTuDacBiet(txtSoGheL1.getText()) == false || ktrKiTuDacBiet(txtSoGheL2.getText()) == false || ktrKiTuDacBiet(txtTinhTrangTau.getText()) == false){
            jlbTT.setText("Số lượng không hợp lệ");
            jlbTT.setForeground(Color.red);
            return;
        }
        else if(Integer.parseInt(txtSoGheL1.getText())<0||Integer.parseInt(txtSoGheL2.getText())<0||Integer.parseInt(txtTinhTrangTau.getText()) < 0)
        {
            jlbTT.setText("Số lượng không hợp lệ");
            jlbTT.setForeground(Color.red);
            return;
        }
        else{
            tau.setTENTAU(txtTenTau.getText());
            tau.setHANGSX(cbHangSX.getSelectedItem().toString());
            tau.setSOGHEL1(Integer.parseInt(txtSoGheL1.getText()));
            tau.setSOGHEL2(Integer.parseInt(txtSoGheL2.getText()));
            int TongSoGheTemp=Integer.parseInt(txtSoGheL1.getText())+Integer.parseInt(txtSoGheL2.getText());
            tau.setTONGSOGHE(TongSoGheTemp);
            tau.setTINHTRANG(Integer.parseInt(txtTinhTrangTau.getText()));
            

            TauDao khdao = new TauDao();
            if(khdao.AddTau(tau) > 0){
                jlbTT.setText("Thành Công");
                jlbTT.setForeground(new Color(11,194,106));
                xoaTrang();
                tblTAUModel.setRowCount(0);
                loadData();
            }
            else{
                jlbTT.setText("Không thành công");
                jlbTT.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_btnThemTauActionPerformed

    private void cbHangSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHangSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHangSXActionPerformed

    private void txtTinhTrangTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinhTrangTauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinhTrangTauActionPerformed

    private void btnRefreshTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTauActionPerformed
        // TODO add your handling code here:
        xoaTrang();
        loadData();
        txtNhapMATAU.setText("");
        jlbTT.setText("");
    }//GEN-LAST:event_btnRefreshTauActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(jTable1.getSelectedRow() >= 0){
            maTau = jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "";
            txtNhapMaTau.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "");
            txtTenTau.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1) + "");
            cbHangSX.setSelectedItem(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2) + "");
            txtSoGheL1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3) + "");
            txtSoGheL2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4) + "");
            txtTongSoGhe.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5) + "");
            txtTinhTrangTau.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6) + "");
        }
        jlbTT.setText("");
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnTimMaTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimMaTauActionPerformed
        // TODO add your handling code here:
        xoaTrang();
        if(txtNhapMATAU.getText().equals("")){
            jlbTT.setText("Không thành công");
            jlbTT.setForeground(Color.red);
            loadData();
        }
        else{
            jlbTT.setText("Thành Công");
            jlbTT.setForeground(new Color(11,194,106));
            loadData_1(txtNhapMATAU.getText());
        }
    }//GEN-LAST:event_btnTimMaTauActionPerformed

    private void txtNhapMaTauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNhapMaTauMouseClicked
        jlbTT.setText("");
    }//GEN-LAST:event_txtNhapMaTauMouseClicked

    private void txtSoGheL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoGheL1MouseClicked
        jlbTT.setText("");
    }//GEN-LAST:event_txtSoGheL1MouseClicked

    private void txtTenTauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenTauMouseClicked
        jlbTT.setText("");
    }//GEN-LAST:event_txtTenTauMouseClicked

    private void txtSoGheL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoGheL2MouseClicked
        jlbTT.setText("");
    }//GEN-LAST:event_txtSoGheL2MouseClicked

    private void txtTongSoGheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTongSoGheMouseClicked
        jlbTT.setText("");
    }//GEN-LAST:event_txtTongSoGheMouseClicked

    private void txtTinhTrangTauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTinhTrangTauMouseClicked
        jlbTT.setText("");
    }//GEN-LAST:event_txtTinhTrangTauMouseClicked

    private void txtNhapMATAUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNhapMATAUMouseClicked
        jlbTT.setText("");
    }//GEN-LAST:event_txtNhapMATAUMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefreshTau;
    private javax.swing.JButton btnSuaTau;
    private javax.swing.JButton btnThemTau;
    private javax.swing.JButton btnTimMaTau;
    private javax.swing.JButton btnXoaTau;
    private javax.swing.JComboBox<String> cbHangSX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlbTT;
    private javax.swing.JTextField txtNhapMATAU;
    private javax.swing.JTextField txtNhapMaTau;
    private javax.swing.JTextField txtSoGheL1;
    private javax.swing.JTextField txtSoGheL2;
    private javax.swing.JTextField txtTenTau;
    private javax.swing.JTextField txtTinhTrangTau;
    private javax.swing.JTextField txtTongSoGhe;
    // End of variables declaration//GEN-END:variables
    
    /*private static class PhoneException extends Exception {

        public PhoneException(String str) {
            super(str);
        }
    }*/
}
